package server.com.Business.models;

/*
 * author: Venkata Prashant
 * Description: This class represents a line in the response of list method
 * 				Class variables are the details of the message.
 * 				toString function is overridden to customize the string message generated by the object
 * 				A constructor is defined to decode each line of response from the string message.
 * 
 * Version: 0.1
 */
public class FileDetails {

	private String fileName;
	private String fileSize;
	private String checkSum;
	public String getFileName() {
		return fileName;
	}
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	public String getFileSize() {
		return fileSize;
	}
	public void setFileSize(String fileSize) {
		this.fileSize = fileSize;
	}
	public String getCheckSum() {
		return checkSum;
	}
	public void setCheckSum(String checkSum) {
		this.checkSum = checkSum;
	}
	/*
	 * Description: server invoked function to encode a file description sent to a peer 
	 * Version:0.1
	 */
	@Override
	public String toString() {
		return "" + fileName + " " + fileSize  + " " + checkSum + "";
	}
	
	/*
	 * Description: peer invoked function to create an object of a file from the message received.
	 * Version:0.1
	 */
	public FileDetails(String message)
	{
		if(message != null)
		{
			String[] messageSplit = message.split(" ");
			this.fileName = messageSplit[0];
			this.fileSize = messageSplit[1];
			this.checkSum = messageSplit[2];
			
		}
	}
    public FileDetails(String filename, String filesize, String checksum)
    {
        if( filename != null && filesize != null && checksum != null )
        {
            this.fileName = filename;
            this.fileSize = filesize;
            this.checkSum = checksum;
        }
    }
    
    public FileDetails()
    {
    	
    }
	
	
}

