package server.com.Business.models;

import java.util.Date;


import server.com.Business.exception.FilePeerException;

/*
 * author: Venkata Prashant
 * Description: This class represents a line in the response of getFileTracker message.
 * 				Class variables are the arguments of the message.
 * 				toString function is overridden to customize the string message generated by the object
 * 				A constructor is defined to decode the each line from the message.
 * 
 * Version: 0.1
 */
public class FilePeers {
	
	private String ipAddress;
	private int portNumber;
	private long startByte;
	private long endByte;
	private Date timeStamp;
	public String getIpAddress() {
		return ipAddress;
	}
	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}
	public int getPortNumber() {
		return portNumber;
	}
	public void setPortNumber(int portNumber) {
		this.portNumber = portNumber;
	}
	public long getStartByte() {
		return startByte;
	}
	public void setStartByte(long startByte) {
		this.startByte = startByte;
	}
	public long getEndByte() {
		return endByte;
	}
	public void setEndByte(long endByte) {
		this.endByte = endByte;
	}
	public Date getTimeStamp() {
		return timeStamp;
	}
	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}
	/*
	 * Description: A server invoker function to encode a peer details sharing the file
	 * Version: 0.1
	 */
	@Override
	public String toString() {
		return "" + ipAddress + ":" + portNumber + ":" + startByte + ":" + endByte + ":" 
				+ timeStamp.getTime() + "";
	}
	
	/*
	 * Description: A peer invoked function to obtain the object of the peer sharing the request file.
	 * Version: 0.1
	 */
	public FilePeers(String message) throws FilePeerException {
		
		if(message != null)
		{
			String[] messageSplit = message.split(":");
			if(messageSplit.length == 5)
			{
				try
				{
					this.ipAddress = messageSplit[0];
					this.portNumber = new Integer(messageSplit[1]);
					this.startByte = new Integer(messageSplit[2]);
					this.endByte = new Integer(messageSplit[3]);
					this.timeStamp = new Date(messageSplit[4]);
					
				}
				catch(Exception e)
				{
					throw new FilePeerException();
				}
			}
			else
			{
				throw new FilePeerException();
			}
		}
		else
		{
			throw new FilePeerException();
		}
	}
	
	public FilePeers()
	{
		
	}
	
	

}
