package server.com.Business.models;

import server.com.Business.exception.GetFileTrackerMessageException;

/*
 * author: Venkata Prashant
 * Description: This class represents the message format for get File tracker message that is exchanged between peer and client.
 * 				Class variables are the arguments of the message.
 * 				toString function is overridden to customize the string message generated by the object
 * 				A constructor is defined to decode the create tracker message from the string message.
 * 
 * Version: 0.1
 */
public class getFileTracker {
	
	private String fileName;

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/*
	 * Description: A peer invoked function to generate string message of the request
	 * Version: 0.1
	 */
	@Override
	public String toString() {
		return "<GET " + fileName + ".track>\n";
	}
	
	/*
	 * Description: A client invoked function to obtain the requesting file details from the message.
	 * Version: 0.1
	 */
	public getFileTracker(String message) throws GetFileTrackerMessageException
	{
		if(message != null)
		{
			message = message.replaceAll(".track", " ");
			String[] messageSplit = message.split(" ");
			if(messageSplit.length == 3)
			{
				try
				{
					this.fileName = messageSplit[1];
				}
				catch(Exception e)
				{
					throw new GetFileTrackerMessageException();
				}
			}
		}
		else
		{
			throw new GetFileTrackerMessageException();
		}
	}
	
	
	public getFileTracker()
	{
		
	}

}
