package com.Business.models;

import java.util.ArrayList;
import java.util.Iterator;

/*
 * author: Venkata Prashant
 * Description: This class represents the response message format for get List message.
 * 				Class variables are the arguments of the message.
 * 				toString function is overridden to customize the string message generated by the object
 * 				A constructor is defined to generate an object from string message.
 * 
 * Version: 0.1
 */
public class RespList {
	
	//contains an array of FileDetails object. Each fileDetails object represents one file that is currently being shared.
	private ArrayList<FileDetails> fileDetails;

	public ArrayList<FileDetails> getFileDetails() {
		return fileDetails;
	}

	public void setFileDetails(ArrayList<FileDetails> fileDetails) {
		this.fileDetails = fileDetails;
	}
	/*
	 * Description: A server invoked function to represent the object as string message.
	 * Version: 0.1
	 */
	@Override
	public String toString() {
		String fileDetailsString = "";
		for(Iterator<FileDetails> ite = fileDetails.iterator();ite.hasNext();)
		{
			FileDetails file = ite.next();
			fileDetailsString = fileDetailsString + " " + file.toString();
		}
		return "RespList" + fileDetailsString + "";
	}
	
	/*
	 * Description: A peer invoked constructor to initialize the obect with values obained from the string message.
	 * Version:0.1
	 */
	public RespList(String message)
	{
		if(message != null)
		{
			String[] messageSplit = message.split(" ");
			this.fileDetails = new ArrayList<FileDetails>();
			for(int lcv =1; lcv < messageSplit.length; lcv++)
			{
				FileDetails file = new FileDetails(messageSplit[lcv]);
				this.fileDetails.add(file);
			}
		}
	}
	

}
